version: 2.1

aliases:
  - &junit-results
      ./dist/junit

orbs:
  browser-tools: circleci/browser-tools@1.1.0
  node: circleci/node@4.7
  aws-ecr: circleci/aws-ecr@7.3.0

executors:
  test-runner:
    docker:
      - image: cimg/node:14.15-browsers
    resource_class: medium

jobs:
  test:
    executor: test-runner
    steps:
      - browser-tools/install-chrome
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: run tests
          command: npm run test:ci
      - store_test_results:
          path: *junit-results
      - store_artifacts:
          path: *junit-results
        

workflows:
  build:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only: ww-cideploymenttest
          context: cloud.codehuddle.org
          repo: codehuddle
          path: ./docker
          tag: 'app-circleci'
